
fork_me_ribbon_url: https://github.com/sunnivin/lesson-code-review
baseurl: "/lesson-code-review"
title: "Code review"
code_review_exercise: https://github.com/sunnivin/exercise-code-review


source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']
exclude: ['LICENSE']

collections:
  episodes:
    output: true
    permalink: /:name/
  # guides are in a collection, otherwise site variables
  # like centralized_workflow_exercise_url are not understood
  guides:
    output: true
    permalink: /:name/
